'use client';

import React, { useState, useEffect } from 'react';
import Head from 'next/head';
import ItemTable from '../components/ItemTable';
import DateSelector from '../components/DatePicker';
import Loader from '../components/Loader';
import { format } from 'date-fns';

type Item = {
  title: string;
  link: string;
};

async function fetchItems(date: Date | null): Promise<Item[]> {
  const formattedDate = date ? format(date, 'yyyyMMdd') : '';
  const res = await fetch(`${process.env.NEXT_PUBLIC_API_URL}?date=${formattedDate}`);
  if (!res.ok) {
    throw new Error('Failed to fetch data');
  }
  return res.json();
}

export default function Home() {
  const [items, setItems] = useState<Item[]>([]);
  const [selectedDate, setSelectedDate] = useState<Date | null>(new Date());
  const [loading, setLoading] = useState<boolean>(true);

  useEffect(() => {
    const fetchData = async () => {
      setLoading(true);
      try {
        const data = await fetchItems(selectedDate);
        setItems(data);
      } catch (err) {
        console.error(err);
      } finally {
        setLoading(false);
      }
    };

    fetchData();
  }, [selectedDate]);

  return (
    <div className="bg-white min-h-screen">
      <Head>
        <title>오늘의 카카오뱅크</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-full bg-white">
        <div className="flex flex-col items-center">
          <DateSelector onDateChange={date => setSelectedDate(date)} />
          {loading ? (
            <Loader />
          ) : (
            <ItemTable items={items} />
          )}
        </div>
      </main>
    </div>
  );
}